title: "A New Path"
author: "Jasmine"
description: "Learning new things everyday. This semester I am learning R programming." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "jngallaw@ncsu.edu"
## twitter_username: "twitteruser"
github_username: "jgally"
linkedin_username: "https://www.linkedin.com/in/jasmine-g-a54030208/"
#facebook_username: username
##flickr_username: username
#instagram_username: username
##pinterest_username: username
##youtube_username: username
##googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################


rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
remote_theme: pages-themes/merlot@v0.2.0  

plugins:
  - jekyll-feed
  - jekyll-sitemap  
  - jekyll-remote-theme

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
